name: Deployment
on:
  push: 
       branches: [ master ]

jobs:
 job_one:
  name: Den
  runs-on: ubuntu-latest
  steps:
  - name: server
    uses: appleboy/ssh-action@master
    with:
       host:     ftpupload.net
       username: epiz_30815428
       key: ${{ PASSWORD }}
       port: 21
       script: |
         cd website
         git pull origin master 
         git status
