on:
  push:
    branches:
      - main
name: Production Deployment
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftpupload.net
        server-dir: htdocs/
        username: epiz_30815428
        password: ${{ secrets.PASSWORD }}
